# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    # Ensure that your git status is not dirty
    ensure_git_status_clean

    build_app(workspace: "Deuro.xcworkspace", scheme: "Deuro")
    upload_to_app_store
  end

  lane :beta do
    # ...
    build_app(workspace: "Deuro.xcworkspace", scheme: "Deuro")
    crashlytics(api_token: "e8bc8ddfc58d3f38d03e64a8c53fcf9cbf4adc64",build_secret: "5483cbf13d43ab7658f9037d0fc3cc75d227f1f138f1b2b7e58b96c3ca83be17")
  end
end
